# Generated by Django 3.0 on 2020-03-28 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ex_points', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('discount_rate', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('purchase_rate', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Products')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('expenses', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Customer')),
                ('product_id', models.ManyToManyField(related_name='product', to='cms.Products')),
                ('quantity', models.ManyToManyField(related_name='store', to='cms.Store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Store'),
        ),
    ]
