# Generated by Django 3.0 on 2020-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200412_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='saving',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
