# Generated by Django 3.0 on 2020-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200412_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometype',
            name='name',
        ),
        migrations.AddField(
            model_name='incometype',
            name='type',
            field=models.CharField(choices=[('S', 'Salary'), ('P', 'Property'), ('B', 'Business'), ('O', 'Other')], default='Salary', max_length=100),
        ),
    ]
