# Generated by Django 3.0 on 2020-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200412_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='type',
            field=models.CharField(choices=[('S', 'Salary'), ('P', 'Property'), ('B', 'Business'), ('O', 'Other')], default='Salary', max_length=1),
        ),
    ]
