# Generated by Django 3.0 on 2020-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200412_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingtype',
            options={},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
        migrations.RemoveField(
            model_name='savingtype',
            name='saving',
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(choices=[('L', 'Lifestyle'), ('E', 'Entertainment'), ('D', 'Donation'), ('ED', 'Eduction'), ('O', 'Other'), ('F', 'Fixed'), ('EQ', 'Equipment')], default='Salary', max_length=2),
        ),
        migrations.AlterField(
            model_name='savingtype',
            name='name',
            field=models.CharField(choices=[('B', 'Bank'), ('O', 'Other')], default='Bank', max_length=2),
        ),
        migrations.DeleteModel(
            name='IncomeType',
        ),
    ]
