# Generated by Django 3.0 on 2020-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200412_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(choices=[('P', 'Property'), ('B', 'Business'), ('O', 'Other'), ('S', 'Salary')], default='Bank', max_length=2),
        ),
    ]
