# Generated by Django 3.0 on 2020-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20200412_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(choices=[('S', 'Salary'), ('O', 'Other'), ('B', 'Business'), ('P', 'Property')], default='Bank', max_length=2),
        ),
    ]
