# Generated by Django 3.0 on 2020-04-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20200412_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(choices=[('O', 'Other'), ('B', 'Business'), ('P', 'Property'), ('S', 'Salary')], default='Bank', max_length=2),
        ),
    ]
