# Generated by Django 3.0 on 2020-04-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20200412_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeType',
        ),
    ]
