# Generated by Django 3.0 on 2020-04-12 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20200412_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('O', 'Other'), ('B', 'Business'), ('P', 'Property'), ('S', 'Salary')], default='Bank', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
