# Generated by Django 3.0 on 2020-04-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20200412_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeType',
        ),
    ]
