# Generated by Django 3.0 on 2020-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20200412_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(choices=[('P', 'Property'), ('O', 'Other'), ('B', 'Business'), ('S', 'Salary')], default='Salary', max_length=2),
        ),
    ]
