# Generated by Django 3.0 on 2020-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20200415_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(choices=[('P', 'Property'), ('O', 'Other'), ('S', 'Salary'), ('B', 'Business')], default='Salary', max_length=2),
        ),
    ]
